version: 2

sources:
  - name: ingested_data
    loader: parquet
    tables:
      - name: raw_companies
        meta:
          external_location: "read_parquet('{{ env_var('DBT_SOURCE_COMPANIES_REGISTRY_PARQUET_EXPORT') }}/companies.parquet')"
        columns:
          - name: company_id
            description: 'Unique identifier for the company (Primary Key).'
            tests:
              - unique
              - not_null
          - name: name
            description: 'The name of the company.'
            tests:
              - not_null
          - name: incorporation_date
            description: 'The date on which the company was incorporated.'
            tests:
              - not_null
          - name: street_address
            description: 'The street address of the company (if available).'
          - name: city
            description: 'The city where the company is located.'
          - name: country_code
            description: "A two-letter code representing the company's country."

      - name: raw_directors
        meta:
          external_location: "read_parquet('{{ env_var('DBT_SOURCE_COMPANIES_REGISTRY_PARQUET_EXPORT') }}/directors.parquet')"
        columns:
          - name: director_id
            description: 'Unique identifier for the director (Primary Key).'
            tests:
              - unique
              - not_null
          - name: company_id
            description: 'Identifier for the company to which the director is associated (Foreign Key).'
            tests:
              - not_null
          - name: first_name
            description: 'The first name of the director.'
            tests:
              - not_null
          - name: last_name
            description: 'The last name of the director.'
            tests:
              - not_null
          - name: appointment_date
            description: 'The date when the director was appointed.'
            tests:
              - not_null
          - name: nationality
            description: 'The nationality of the director.'

      - name: raw_financials
        meta:
          external_location: "read_parquet('{{ env_var('DBT_SOURCE_COMPANIES_REGISTRY_PARQUET_EXPORT') }}/financials.parquet')"
        columns:
          - name: financial_id
            description: 'Unique identifier for the financial record (Primary Key).'
            tests:
              - unique
              - not_null
          - name: company_id
            description: 'Identifier for the company associated with this financial record (Foreign Key).'
            tests:
              - not_null
          - name: report_date
            description: 'The date of the financial report.'
            tests:
              - not_null
          - name: revenue
            description: 'The revenue amount as reported.'
            tests:
              - not_null
          - name: profit
            description: 'The profit amount as reported.'
            tests:
              - not_null

      - name: raw_peps
        meta:
          external_location: "read_parquet('{{ env_var('DBT_SOURCE_PEPS_PARQUET_EXPORT') }}/peps.parquet')"
        columns:
          - name: first_name
            description: 'The first name of the politically exposed person.'
            tests:
              - not_null
          - name: last_name
            description: 'The last name of the politically exposed person.'
            tests:
              - not_null
          - name: position
            description: 'The position or role held by the person.'
            tests:
              - not_null
          - name: country
            description: 'The country associated with the person.'
            tests:
              - not_null

      - name: raw_risky_locations
        meta:
          external_location: "read_parquet('{{ env_var('DBT_SOURCE_RISKY_LOCATIONS_PARQUET_EXPORT') }}/risky_locations.parquet')"
        columns:
          - name: city
            description: 'The name of the city location considered risky.'
            tests:
              - not_null
          - name: country
            description: 'The name of the country code location considered risky.'
            tests:
              - not_null
          - name: risk_level
            description: 'The level of risk associated with the location (e.g., High, Medium).'
            tests:
              - not_null
